services:
  - type: web
    name: marketlinklogistics
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run init-db && npm run migrate:pg:ddl && npm run migrate:pg && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        value: marketlink_logistics_secret_key_2024
      - key: DB_PATH
        value: /data/logistics.db
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_EMAIL
        value: admin@marketlinklogistics.com
      - key: ALLOW_ADMIN_FALLBACK
        value: "false"
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: marketlink-postgres
          property: connectionString
      - key: ORIGIN_WHITELIST
        value: "https://your-domain.com,https://your-onrender-url.onrender.com"
      - key: PUBLIC_URL
        value: "https://market-link-logistics.onrender.com"
      - key: MAIL_HOST
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USER
        value: apikey
      - key: MAIL_API_KEY
        value: ""
      - key: MAIL_FROM
        value: "no-reply@your-domain.com"
      - key: SESSION_MAX_AGE_MINUTES
        value: 30
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1

postgres:
  - name: marketlink-postgres
    plan: free 